import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import "@/styles/fonts.css";
import "@/styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <div className="max-w-screen-lg mx-auto px-8">
          <Header/>
          <div>
            {children}
          </div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}