import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import "@/styles/fonts.css";
import "@/styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <div className="flex flex-col mh-svh">
          <Header/>
          <main className="flex-1">
            {children}
          </main>
          <Footer/>
        </div>
      </body>
    </html>
  );
}