import "@/style/globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body
        className="antialiased"
      >
        <div className="max-w-5xl mx-auto min-h-dvh">
          {children}
        </div>        
      </body>
    </html>
  );
}
